# coding: utf-8

"""
    Megaputer Text Mining API

    Megaputer Text Mining API  # noqa: E501

    OpenAPI spec version: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class FactsResponsePositions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'sentence': 'int',
        'begin': 'int',
        'length': 'int'
    }

    attribute_map = {
        'sentence': 'sentence',
        'begin': 'begin',
        'length': 'length'
    }

    def __init__(self, sentence=None, begin=None, length=None):  # noqa: E501
        """FactsResponsePositions - a model defined in OpenAPI"""  # noqa: E501

        self._sentence = None
        self._begin = None
        self._length = None
        self.discriminator = None

        if sentence is not None:
            self.sentence = sentence
        if begin is not None:
            self.begin = begin
        if length is not None:
            self.length = length

    @property
    def sentence(self):
        """Gets the sentence of this FactsResponsePositions.  # noqa: E501

        Sentence index  # noqa: E501

        :return: The sentence of this FactsResponsePositions.  # noqa: E501
        :rtype: int
        """
        return self._sentence

    @sentence.setter
    def sentence(self, sentence):
        """Sets the sentence of this FactsResponsePositions.

        Sentence index  # noqa: E501

        :param sentence: The sentence of this FactsResponsePositions.  # noqa: E501
        :type: int
        """

        self._sentence = sentence

    @property
    def begin(self):
        """Gets the begin of this FactsResponsePositions.  # noqa: E501

        Index of first token of fact  # noqa: E501

        :return: The begin of this FactsResponsePositions.  # noqa: E501
        :rtype: int
        """
        return self._begin

    @begin.setter
    def begin(self, begin):
        """Sets the begin of this FactsResponsePositions.

        Index of first token of fact  # noqa: E501

        :param begin: The begin of this FactsResponsePositions.  # noqa: E501
        :type: int
        """

        self._begin = begin

    @property
    def length(self):
        """Gets the length of this FactsResponsePositions.  # noqa: E501

        Number of tokens in fact  # noqa: E501

        :return: The length of this FactsResponsePositions.  # noqa: E501
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this FactsResponsePositions.

        Number of tokens in fact  # noqa: E501

        :param length: The length of this FactsResponsePositions.  # noqa: E501
        :type: int
        """

        self._length = length

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FactsResponsePositions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
