# coding: utf-8

"""
    Megaputer Text Mining API

    Megaputer Text Mining API  # noqa: E501

    OpenAPI spec version: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SentimentsResponseSentiments(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'attributes': 'SentimentsResponseAttributes',
        'positions': 'list[SentimentsResponsePositions]'
    }

    attribute_map = {
        'type': 'type',
        'attributes': 'attributes',
        'positions': 'positions'
    }

    def __init__(self, type=None, attributes=None, positions=None):  # noqa: E501
        """SentimentsResponseSentiments - a model defined in OpenAPI"""  # noqa: E501

        self._type = None
        self._attributes = None
        self._positions = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if attributes is not None:
            self.attributes = attributes
        if positions is not None:
            self.positions = positions

    @property
    def type(self):
        """Gets the type of this SentimentsResponseSentiments.  # noqa: E501

        Sentiment type  # noqa: E501

        :return: The type of this SentimentsResponseSentiments.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SentimentsResponseSentiments.

        Sentiment type  # noqa: E501

        :param type: The type of this SentimentsResponseSentiments.  # noqa: E501
        :type: str
        """
        allowed_values = ["Positive", "Negative"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def attributes(self):
        """Gets the attributes of this SentimentsResponseSentiments.  # noqa: E501


        :return: The attributes of this SentimentsResponseSentiments.  # noqa: E501
        :rtype: SentimentsResponseAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this SentimentsResponseSentiments.


        :param attributes: The attributes of this SentimentsResponseSentiments.  # noqa: E501
        :type: SentimentsResponseAttributes
        """

        self._attributes = attributes

    @property
    def positions(self):
        """Gets the positions of this SentimentsResponseSentiments.  # noqa: E501

        Sentiment positions in text  # noqa: E501

        :return: The positions of this SentimentsResponseSentiments.  # noqa: E501
        :rtype: list[SentimentsResponsePositions]
        """
        return self._positions

    @positions.setter
    def positions(self, positions):
        """Sets the positions of this SentimentsResponseSentiments.

        Sentiment positions in text  # noqa: E501

        :param positions: The positions of this SentimentsResponseSentiments.  # noqa: E501
        :type: list[SentimentsResponsePositions]
        """

        self._positions = positions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SentimentsResponseSentiments):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
