# coding: utf-8

"""
    Megaputer Text Mining API

    Megaputer Text Mining API  # noqa: E501

    OpenAPI spec version: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TotalLimitConstantResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ntu_limit': 'int',
        'ntu': 'int'
    }

    attribute_map = {
        'ntu_limit': 'NTULimit',
        'ntu': 'NTU'
    }

    def __init__(self, ntu_limit=None, ntu=None):  # noqa: E501
        """TotalLimitConstantResponse - a model defined in OpenAPI"""  # noqa: E501

        self._ntu_limit = None
        self._ntu = None
        self.discriminator = None

        if ntu_limit is not None:
            self.ntu_limit = ntu_limit
        if ntu is not None:
            self.ntu = ntu

    @property
    def ntu_limit(self):
        """Gets the ntu_limit of this TotalLimitConstantResponse.  # noqa: E501

        The maximum number of text units that can be processed in all time  # noqa: E501

        :return: The ntu_limit of this TotalLimitConstantResponse.  # noqa: E501
        :rtype: int
        """
        return self._ntu_limit

    @ntu_limit.setter
    def ntu_limit(self, ntu_limit):
        """Sets the ntu_limit of this TotalLimitConstantResponse.

        The maximum number of text units that can be processed in all time  # noqa: E501

        :param ntu_limit: The ntu_limit of this TotalLimitConstantResponse.  # noqa: E501
        :type: int
        """

        self._ntu_limit = ntu_limit

    @property
    def ntu(self):
        """Gets the ntu of this TotalLimitConstantResponse.  # noqa: E501

        Counter of text units that have been already processed  # noqa: E501

        :return: The ntu of this TotalLimitConstantResponse.  # noqa: E501
        :rtype: int
        """
        return self._ntu

    @ntu.setter
    def ntu(self, ntu):
        """Sets the ntu of this TotalLimitConstantResponse.

        Counter of text units that have been already processed  # noqa: E501

        :param ntu: The ntu of this TotalLimitConstantResponse.  # noqa: E501
        :type: int
        """

        self._ntu = ntu

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TotalLimitConstantResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
